version: '3.3'
services:
    laravel-docker:
        container_name: laravel-docker
        build: ./
        ports:
            - 9001:80
        volumes:
            - ./:/usr/share/nginx/html/
        restart: always
        depends_on:
            - database-docker
        networks:
            - laravel-network
    database-docker:
        container_name: database-docker
        image: mysql
        volumes:
            - ./dbdata/:/var/lib/mysql/
        ports:
            - 9002:3306
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: social_network
            MYSQL_USER: admin
            MYSQL_PASSWORD: root
        networks:
            - laravel-network

networks:
    laravel-network:
        driver: bridge
